# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG Tbilis DevFest 2016 Madafacka"
email: "devfest@gdg.org.ua"
description: "GDG DevFest is a set of events all around the world"
baseurl: "" #/zeppelin
url: "https://irakligeo.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Tbilisi"
organizerAlternateName: "Google Developer Group Tbilisi"
organizerDescription: "მოხალისე ჭკვიანი და ტექნოლოგიების მოყვარული ადამიანები, რომლებიც მუშაობენ ინოვაციურ პროექტებზე და უზიარებენ გამოცდილებას გუგლის ტექნოლოგიების შესახებ სხვებს."
organizerEmail: "lviv@gdg.org.ua"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
# navigationLinks:
#  - {permalink: "/", text: "Home"}
#  - {permalink: "/blog/", text: "Blog"}
#  - {permalink: "/schedule/", text: "Schedule"}
#  - {permalink: "/speakers/", text: "Speakers"}
#  - {permalink: "/team/", text: "Team"}
#  - {permalink: "/logistics/", text: "Logistics"}
#  - {permalink: "/hackathon/", text: "Hackathon"}
# bottomNavigationLinks:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
# rightNavigationButtons:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
navigationLinks:
 - {permalink: "/", text: "მთავარი"}
 - {permalink: "/blog/", text: "სიახლეები"}
 - {permalink: "/schedule/", text: "განრიგი"}
 - {permalink: "/speakers/", text: "სპიკერები"}
 - {permalink: "/team/", text: "ჩვენ"}
 # - {permalink: "/hackathon/", text: "ჰაკათონი"}
bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "გახდი სპიკერი"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "გახდი სპიკერი"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest <typeout> 2016"
eventDate: "ნოემბერი 27, 2016"
typeoutTextValues: '"", "Tbilisi"'
typeoutFallback: "Season"
heroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "გახდი სპიკერი"}
 - {link: "https://bit.ly/dfua-c4p", text: "დარეგისტრირდი"}
 # - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "GDG DevFest-ის შესახებ"
aboutBlock:
 - {title: "კონფერენცია", image: "conference.jpg", text: "GDG–ის ყოველწლიური დეველოპერული ფესტივალი საქართველოში. Google-ის წარმომადგენლები, საინტერესო სპიკერები და განსაკუთრებული ღონისძიება სპეციალურად GDG თბილისისთვის." }
 - {title: "ვორქშოფები", image: "workshop.jpg", text: "2 საათიანი პრაქტიკული ლექცია, რომელზეც მონაწილეები თავად შექმნიან მარტივ აპლიკაციებსა და დიზაინს. ბევრი პროგრამირება, ინოვაცია და ტექნოლოგია." }
 # - {title: "ჰაკათონი", image: "hackathon.jpg", text: "48 საათიანი ღონისძიება. გააქვთ ტექნოლოგიებთან დაკავშირებული ინოვაციური იდეა? შემოგვიერთდით ჰაკათონზე და აქციეთ ის რეალობად!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "50", specialCharacter: "+", info: "დამსწრეები", detail: "მსოფლიოს მასშტაბით"}
 - {count: "48", specialCharacter: "+", info: "საათი", detail: "წმინდა Google-ის ტექნოლოგიები"}
 - {count: "15", specialCharacter: "+", info: "სპიკერები", detail: "საქართველოდან და არა მხოლოდ"}
 - {count: "3", specialCharacter: "", info: "პარალელური აქტივობა", detail: "დამატებით გასართობი ლაბი"}

# Latest News Block
latestNewsTitle: "სიახლეები"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "ძერსკი სპიკერები"
rockstarSpeakersButtonText: "ნახეთ ყველა სპიკერი"

# Location Block
locationBlockTitle: "მისამართი"
eventLocationName: "ჯეოლაბი"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "მერაბ ალექსიძის 8"
eventAddressLocality: "თბილისი"
eventAddressLocalityRegion: "საქართველო"
eventPostalCode: "0160"
eventAddressCountry: "საქართველო"
eventStartTime: "2015-11-07T11:00"
eventDoorTime: "10:00"
eventEndTime: "2015-11-08T20:00"
eventPlaceCoordinates: "41.717753, 44.784889"
mapCenterCoordinates: "41.717753, 44.784889"
mapMobileCenterCoordinates: "41.717753, 44.784889"

# Venue Block
venueBlockTitle: "ჯეოლაბი"
venueBigImage: "geolab_1.jpg"
venueSmallImage1: "geolab_2.jpg"
venueSmallImage2: "geolab_3.jpg"
venueSmallImage3: "geolab_4.jpg"
venueTitle: "ჯეოლაბის ლაბორატორია"
venueFeatures: ["მობილური და ვებ აპლიკაციების ლაბორატორია, რომელიც 24 საათის განმავლობაში ღიაა საინტერესო და ინოვაციური პროექტებისთვის."]
# venueFeatures: ["24/7-ზე სამუშაო გარემო", "საინტერესო ტექნიკით აღჭურვილი", "ქალაქის ცენტრში"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "ორგანიზატორები"
partnersTitle: "პარტნიორები"
partnersC4sponsorsButton: "გახდი სპონსორი"

# # Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "გამოიწერე სიახლეები"
# subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
# ticketsTitle: "Pricetable"
# ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
# ticketsOffers:
#  -
#   name: "Early Bird"
#   price: "350"
#   priceCurrency: "UAH"
#   ticketsNumber: "150"
#   ribbon: "-5%"
#   buyButtonLink: "http://dfua.ticketforevent.com/"
#   buyButtonText: "Buy Now"
#   ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#   validFrom: "2014-08-25T10:00"
#   validThrough: "2014-09-30T23:59"
#  -
#   name: "Last Chance"
#   price: "450"
#   priceCurrency: "UAH"
#   ticketsNumber: "100"
#   ribbon: "-20%"
#   featured: true
#   buyButtonLink: "http://dfua.ticketforevent.com/"
#   buyButtonText: "Buy Now"
#   ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#   validFrom: "2014-10-01T00:00"
#   validThrough: "2014-10-23T23:59"
#   disabled: true
#  -
#   name: "Student"
#   price: "200"
#   priceCurrency: "UAH"
#   ticketsNumber: "50"
#   buyButtonLink: "http://dfua.ticketforevent.com/"
#   buyButtonText: "Buy Now"
#   additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
#   ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#   validFrom: "2014-08-20T10:00"
#   validThrough: "2014-10-23T23:59"
#   soldOut: true
#   soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://facebook.com/gdgtbilisi", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "ბმულები"
  links:
    - {link: "https://developers.google.com", text: "Google Developers"}
   # - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
 -
  title: "კონტაქტები"
  links:
   - {link: "mailto:lviv@gdg.org.ua", text: "lviv@gdg.org.ua"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "სიახლეები"
blogCommentsEnabled: false
discusShortName: "devfestua"

# Speakers List Block
showSessions: false

# Team Block
teamBlockTitle: "ჩვენ შესახებ"
aboutUs: "GDG თბილისი, 2012 წლის იანვარში დაარსდა. მისი ვირტუალური ჯგუფი 1000-მდე მეტ ქართველ  დეველოპერს აერთიანებს. ღონისძიებებზე დამსწრეთა საშუალო აქტივობა კი 50–70 ადამიანს შეადგენს. 1 წლის განმავლობაში ჩატარებული ღონისძიებებისა და აქტიურობის შედეგად თბილისის ჯგუფი, მსოფლიოს 300–ზე მეტ ჯგუფს შორის, ათეულში და ხუთეულშიც კი მოხვედრილა. GDG თბილისის ფარგლებში ხდება ცოდნისა და გამოცდილების გაცვლა, Google-ის თანამშრომლებთან პირდაპირი კავშირების დამყარება, უახლესი ტენდენციებისა და ტექნოლოგიების განხილვა, ახალგაზრდა პროგრამისტების მიერ აპლიკიებზე მუშაობის წახალისება და სხვ. GDG თბილისმა ერთხელ უკვე წარმატებით უმასპინძლა ქალთა დეველოპერულ ფესტივალ DevfestW-სა და რეგიონალური დონის Ecahack ჰაკერულ მარათონს. Google–ის დეველოპერების ჯგუფის ყოველწლიური დეველოპერული ფესტივალი Devfest საქართველოში მესამედ გაიმართება. წელს ამ ღონისძიების თანაორგანიზატორი და მასპინძელი საქართველოში GeoLab-ი იქნება. ჯეოლაბი წარმოადგენს მობილური და ვებ აპლიკაციების ლაბორატორიას. ეს არის სივრცე, რომელიც 24 საათის განმავლობაში ღიაა სხვადასხვა საინტერესო და ინოვაციური პროექტების განხორციელებისათვის. ჯეოლაბი აღჭურვილია უახლესი ტექნოლოგიებით და ყოველთვის მზადაა დაგეხმაროთ, კრეატიული აზროვნებისა და ტექნიკური უნარ–ჩვევების რეალიზებაში. ჯეოლაბის განუყოფელი ნაწილია სასწავლო ცენტრი. აქ ნებისმიერ მსურველს სხვადასხვა სპეციალობიდან შეუძლია აირჩიოს ერთ-ერთი და 3 თვის განმავლობაში დაეუფლოს მისთვის საინტერესო პროფესიას. მათ ვისაც არ აქვს საბაზისო ცოდნა, ჯეოლაბი ასევე სთავაზობს მოკლე, 2 თვიან კურსებს. ჩვენთან თქვენ შეგიძლიათ თავად შექმნათ პროგრამული პროდუქტი, შეიმუშაოთ ვებ-გვერდის ან მობილური აპლიკაციის დიზაინი, დააპროექტოთ და მართოთ პროგრამულ სფეროსთან დაკავშირებული პროექტები."
# aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "ჰაკათონი"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "ჰაკათონის თემა"
hackathonRows:
- {title: "Android ", image: "hackathon-0.png", details: "„ჯეოლაბი“ ვებ ან მობილური აპლიკაციების დეველოპერებსა და დიზაინერებს დაუვიწყარ 2 დღიან შეჯიბრს ჰპირდება! ჰაკათონი არის 2 დღიანი შეჯიბრი, ვებ ან მობილური აპლიკაციების დეველოპერებისთვის და დიზაინერებისთვის. ჰაკათონში მონაწილე აუცილებლად საქართველოს რომელიმე უნივერსიტეტის სტუდენტი უნდა იყოს. ჰაკათონის გახსნის წუთიდან მონაწილეები 48 საათის განმავლობაში საკუთარ პროექტებს შექმნიან. ჰაკათონის პროექტში გუნდმა Google-ის ერთ-ერთი სერვისი აუცილებლად უნდა გამოიყენოს. ჯეოლაბი მთელი ჰაკათონის მსვლელობისას, თქვენთვის უზრუნველყოფს მყუდრო და ინოვაციურ გარემოს, კვებას, მაისურებსა და შესანიშნავ მოგონებებს. ჰაკათონის მონაწილეთა რაოდენობა შეზღუდულია: ჰაკათონში მონაწილეობას მხოლოდ პირველი 40 რეგისტრირებული სტუდენტი მიიღებს. ერთ გუნდში მაქსიმუმ 3 მონაწილე; რა უნდა წარმოადგინოთ ჰაკათონზე? პირადობის მოწმობა, სტუდენტობის დამადასტურებელი საბუთი (სტუდენტის მოწმობა, ან რაიმე სხვა დოკუმენტი, რომელიც ადასტურებს რომ სტუდენტი ხართ), თქვენი ლეპტოპი და ყველა ის ნივთი, რომელიც ამ ხნის განმავლობაში, შეჯიბრზე ყოფნისას დაგჭირდებათ." } 
 # - {title: "Android ", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 # - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 # - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "ჟიური"

#Hackathon Prizes Block
prizesTitle: "პრიზები"
prizes:
 - {title: "მე-2 ადგილი", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1-ლი ადგილი", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "მე-3 ადგილი", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "ადგილმდებარეობა"
hackathonLocationName: "ჯეოლაბი"
hackathonLocationLink: "http://geolab.edu.ge"
hackathonStreetAddress: "მერაბ ალექსიძის 8"
hackathonAddressLocality: "თბილისი"
hackathonAddressLocalityRegion: "საქართველო"
hackathonPostalCode: "0160"
hackathonAddressCountry: "საქართველო"
hackathonTimeTitle: "ჰაკინგი"
hackathonStartTime: "2015-11-06T20:00"
hackathonDoorTime: "20:00"
hackathonEndTime: "2015-11-08T18:00"
viewOnMap: "ნახეთ Google-ის რუკაზე"
hackathonPlaceCoordinates: "41.717753, 44.784889"
hackathonMapCenterCoordinates: "41.717753, 44.784889"
hackathonMapMobileCenterCoordinates: "41.717753, 44.784889"
